const express = require('express');
const multer = require('multer');
const path = require("path");
const fs = require("fs");

var PORT = process.env.PORT || 3000;
const upload = multer({
  dest: 'uploads/' // this saves your file into a directory called "uploads"
}); 

const app = express();

app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});

// It's very crucial that the file name matches the name attribute in your html
app.post('/', upload.single('file-to-upload'), (req, res) => {
  // res.redirect('/');
  const tempPath = req.file.path;
  const targetPath = path.join(__dirname, "./uploads/" + req.file.originalname);
  console.log(req.file.originalname);
  if( (path.extname(req.file.originalname).toLowerCase() === ".png") ||
    (path.extname(req.file.originalname).toLowerCase() === ".jpeg")  )
  {
    fs.rename(tempPath, targetPath, err => {
      if (err) return handleError(err, res);
    
       res
       .status(200)
       .contentType("text/plain")
       .end("File uploaded!");
      
       cloudinaryTest();
      }
     
    ) }
   else {
    fs.unlink(tempPath, err => {
      if (err) return handleError(err, res);

      res
        .status(403)
        .contentType("text/plain")
        .end("Only .png or jpeg files are allowed!");
    });
  }
}
);

function cloudinaryTest(){
// var fs = require('fs');
var cloudinary = require('cloudinary').v2;


var uploads = {};

// set your env variable CLOUDINARY_URL or set the following configuration
cloudinary.config({
  cloud_name: 'dycolznuv',
  api_key: '476479364861483',
  api_secret: 'Sc9ubTr2hHvIg5hwi7ljRTpqz3w'
});



console.log( "** ** ** ** ** ** ** ** ** Uploads ** ** ** ** ** ** ** ** ** **");

// File upload
cloudinary.uploader.upload('uploads/test1.png',{tags:'basic_sample'},function(err,image){
  console.log();
  console.log("** File Upload");
  if (err){ console.warn(err);}
  console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
  console.log("* "+image.public_id);
  console.log("* "+image.url);
  console.log("Image tag: " + image.tags);
//   waitForAllUploads("Bird",err,image);
});
}


// app.listen(3000);

app.listen(PORT, function() {
    console.log(`🌎  ==> API Server now listening on PORT ${PORT}!`);
  });
  
